// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvtfgC10MY1auPuNR1aW_H7bjJPi2yk94',
    appId: '1:133449191969:web:37be3ff2ba1289a77fc960',
    messagingSenderId: '133449191969',
    projectId: 'smart-recycle-3106f',
    authDomain: 'smart-recycle-3106f.firebaseapp.com',
    storageBucket: 'smart-recycle-3106f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RYVzLEbXrH-7cNlp-55N2yujXm4NaFY',
    appId: '1:133449191969:android:413d95716693e36f7fc960',
    messagingSenderId: '133449191969',
    projectId: 'smart-recycle-3106f',
    storageBucket: 'smart-recycle-3106f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1r0bA8iBMjl65CzjKn9DcD71RbcOyg8',
    appId: '1:133449191969:ios:92f8c8ffc1a9eff67fc960',
    messagingSenderId: '133449191969',
    projectId: 'smart-recycle-3106f',
    storageBucket: 'smart-recycle-3106f.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartRecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1r0bA8iBMjl65CzjKn9DcD71RbcOyg8',
    appId: '1:133449191969:ios:92f8c8ffc1a9eff67fc960',
    messagingSenderId: '133449191969',
    projectId: 'smart-recycle-3106f',
    storageBucket: 'smart-recycle-3106f.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartRecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvtfgC10MY1auPuNR1aW_H7bjJPi2yk94',
    appId: '1:133449191969:web:091c00eed9e2fb197fc960',
    messagingSenderId: '133449191969',
    projectId: 'smart-recycle-3106f',
    authDomain: 'smart-recycle-3106f.firebaseapp.com',
    storageBucket: 'smart-recycle-3106f.firebasestorage.app',
  );

}